export enum TypeSender {
  EMAIL = 'EMAIL',
  SLACK = 'SLACK',
  SMS = 'SMS',
}

export enum ContentRequestOTP {
  VERIFY_OTP = 'VERIFY_OTP',
  RESET_PASSWORD = 'RESET_PASSWORD',
  VERIFY_PHONE_NUMBER = 'VERIFY_PHONE_NUMBER',
  VERIFY_EMAIL = 'VERIFY_EMAIL',
  CREATE_CUSTOMER = 'CREATE_CUSTOMER',
  CREATE_SUPPLIER = 'CREATE_SUPPLIER',
  DELETE_ACCOUNT = 'DELETE_ACCOUNT',
}
